name: Update Latest PR Date

on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths-ignore:
      - '/data/date.json'

jobs:
  update-date:
    if: 
      github.event.pull_request.merged == true && 
      contains(github.event.pull_request.labels.*.name, 'release')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install date-fns
        run: npm install date-fns date-fns-tz

      - name: Get and format PR merged date in JST
        id: get_formatted_pr_date
        run: |
          LATEST_PR_DATE_UTC="${{ github.event.pull_request.merged_at }}"
          FORMATTED_JST_DATE=$(node -e "
            const { format } = require('date-fns');
            const { toZonedTime } = require('date-fns-tz');
            const utcDate = new Date('$LATEST_PR_DATE_UTC');
            const jstDate = toZonedTime(utcDate, 'Asia/Tokyo');
            const formattedDate = format(jstDate, 'yyyy-MM-dd HH:mm');
            console.log(formattedDate);
          ")
          echo "{\"latestPrMergedAt\": \"$FORMATTED_JST_DATE\"}" > /data/date.json
          
      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add date.json
          git commit -m "リリース日時の更新"
          git push
