name: Update Latest PR Date

on:
  push:
    branches:
      - main

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Get latest merged PR date
        id: get_pr_date
        run: |
          LATEST_PR_DATE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls?state=closed&base=main&sort=updated&direction=desc&per_page=1" | \
            jq -r '.[0].merged_at')
          echo "{\"latestPrMergedAt\": \"$LATEST_PR_DATE\"}" > date.json
          
      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet date.json; then
            echo "Changes detected in date.json. Committing and pushing..."
            git add date.json
            git commit -m "Update latest PR date [skip ci]"
            git push
            echo "Committed and pushed date.json."
          else
            echo "No changes detected in data.json. Skipping commit and push."
          fi
