name: Update Latest PR Date

on:
  push:
    branches:
      - main

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # persist-credentials: false を削除し、デフォルトの GITHUB_TOKEN を使用します。
          # GITHUB_TOKEN はデフォルトで persist-credentials: true のように振る舞い、
          # このトークンでのプッシュは通常、ワークフローを再トリガーしません。
          token: ${{ secrets.GITHUB_TOKEN }} # 明示的に GITHUB_TOKEN を渡す

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Get latest merged PR date
        id: get_pr_date
        run: |
          LATEST_PR_DATE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls?state=closed&base=main&sort=updated&direction=desc&per_page=1" | \
            jq -r '.[0].merged_at')

          echo "Latest PR date: $LATEST_PR_DATE"

          # ★ここから修正・追加★
          # 既存の data.json があれば削除
          if [ -f data.json ]; then
            echo "Deleting existing data.json..."
            rm data.json
          fi

          # data.json を新規作成/上書き
          echo "{\"latestPrMergedAt\": \"$LATEST_PR_DATE\"}" > data.json

          echo "--- Content of generated data.json ---"
          cat data.json
          echo "--------------------------------------"
          
      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
          echo "--- Checking for changes to data.json ---"
          # 変更があるか確認し、あればコミットしてプッシュ
          if ! git diff --quiet data.json; then
            echo "Changes detected in data.json. Committing and pushing..."
            git add data.json
            git commit -m "Update latest PR date [skip ci]"
            git push
            echo "Committed and pushed data.json."
          else
            echo "No changes detected in data.json. Skipping commit and push."
          fi
